#!/usr/bin/env bash
set -euo pipefail

WS="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ "${1:-}" =~ ^(task|gui|prompt-gui)$ && "$#" -eq 1 ]]; then
  exec "$WS/start_prompt_gui.sh" --demo medical_keypoint
fi

export KEYPOINT_DEBUG_ONLY="${KEYPOINT_DEBUG_ONLY:-true}"
export START_KEYPOINT_VIEWER="${START_KEYPOINT_VIEWER:-true}"
export KEYPOINT_DEBUG_TIMEOUT_SEC="${KEYPOINT_DEBUG_TIMEOUT_SEC:-120}"
export KEYPOINT_DEBUG_AUTO_ADVANCE="${KEYPOINT_DEBUG_AUTO_ADVANCE:-false}"
export KEYPOINT_DEBUG_PROMPT_REPUBLISH_SEC="${KEYPOINT_DEBUG_PROMPT_REPUBLISH_SEC:-1.0}"
export KEYPOINT_DEBUG_STATUS_HEARTBEAT_SEC="${KEYPOINT_DEBUG_STATUS_HEARTBEAT_SEC:-1.0}"
export KEYPOINT_VIEWER_DISPLAY_SCALE="${KEYPOINT_VIEWER_DISPLAY_SCALE:-2.2}"
export KEYPOINT_VIEWER_STATUS_PANEL_WIDTH="${KEYPOINT_VIEWER_STATUS_PANEL_WIDTH:-380}"
export KEYPOINT_VIEWER_FOLLOW_WINDOW_RESIZE="${KEYPOINT_VIEWER_FOLLOW_WINDOW_RESIZE:-true}"
export KEYPOINT_VIEWER_PREFER_OVERLAY_IMAGE="${KEYPOINT_VIEWER_PREFER_OVERLAY_IMAGE:-false}"
export PYBULLET_SHOW_KEYPOINT_OVERLAY="${PYBULLET_SHOW_KEYPOINT_OVERLAY:-true}"
export SIM_GUI="true"
export PYBULLET_KEYPOINT_OVERLAY_RADIUS_M="${PYBULLET_KEYPOINT_OVERLAY_RADIUS_M:-0.012}"
export PYBULLET_KEYPOINT_OVERLAY_CROSS_SIZE_M="${PYBULLET_KEYPOINT_OVERLAY_CROSS_SIZE_M:-0.045}"
export PYBULLET_KEYPOINT_OVERLAY_NORMAL_LENGTH_M="${PYBULLET_KEYPOINT_OVERLAY_NORMAL_LENGTH_M:-0.080}"

export OPEN_VOCAB_TARGETS="${OPEN_VOCAB_TARGETS:-true}"
export ENABLE_GRIPPER="${ENABLE_GRIPPER:-false}"
export ENABLE_GRASP_ACTIONS="${ENABLE_GRASP_ACTIONS:-true}"
export SIM_SCENE_PRESET="${SIM_SCENE_PRESET:-medical_grasp}"
export MEDICAL_GRASP_SCISSORS_FIXED="${MEDICAL_GRASP_SCISSORS_FIXED:-true}"
export MEDICAL_GRASP_SCISSORS_GRASPABLE="${MEDICAL_GRASP_SCISSORS_GRASPABLE:-false}"
export EXTERNAL_SCENE_OBJECTS_JSON="${EXTERNAL_SCENE_OBJECTS_JSON:-[]}"
export EXTERNAL_SCENE_OBJECTS_FILE="${EXTERNAL_SCENE_OBJECTS_FILE:-}"
export STABILIZE_RESTING_GRASPABLES="${STABILIZE_RESTING_GRASPABLES:-false}"
export RESTING_TABLE_CLEARANCE_M="${RESTING_TABLE_CLEARANCE_M:-0.0}"
export RESTING_SNAP_MARGIN_M="${RESTING_SNAP_MARGIN_M:-0.025}"
export RESTING_LINEAR_SPEED_TH_MPS="${RESTING_LINEAR_SPEED_TH_MPS:-0.020}"
export RESTING_ANGULAR_SPEED_TH_RADPS="${RESTING_ANGULAR_SPEED_TH_RADPS:-0.080}"
export RESTING_REANCHOR_DELAY_SEC="${RESTING_REANCHOR_DELAY_SEC:-0.60}"
export RESTING_INTERACTION_RELEASE_RADIUS_M="${RESTING_INTERACTION_RELEASE_RADIUS_M:-0.160}"

export SAM3_PROMPT="${SAM3_PROMPT:-left silver surgical instrument}"
export SAM3_SCORE_TH="${SAM3_SCORE_TH:-0.05}"
export SAM3_IMAGE_TOPIC="${SAM3_IMAGE_TOPIC:-/sim/camera/color/image_raw}"
export SAM3_PROMPT_TOPIC="${SAM3_PROMPT_TOPIC:-/sam3/prompt}"
export SAM3_ACTIVE_PROMPT_TOPIC="${SAM3_ACTIVE_PROMPT_TOPIC:-/sam3/active_prompt}"
export SAM3_MASK_TOPIC="${SAM3_MASK_TOPIC:-/sam3/mask}"
export SAM3_SCORE_TOPIC="${SAM3_SCORE_TOPIC:-/sam3/score}"
export FUSION_MIN_SCORE="${FUSION_MIN_SCORE:-0.03}"
export TRACKER_TARGET_TIMEOUT_SEC="${TRACKER_TARGET_TIMEOUT_SEC:-4.0}"

export LLM_BACKEND="${LLM_BACKEND:-qwen3_local}"
export GPU_EXECUTION_MODE="${GPU_EXECUTION_MODE:-staged_single_gpu}"
export QWEN3_AUTO_START="${QWEN3_AUTO_START:-true}"
export QWEN3_STOP_EXTERNAL="${QWEN3_STOP_EXTERNAL:-true}"
export ALLOW_LOCAL_PLANNER_FALLBACK="${ALLOW_LOCAL_PLANNER_FALLBACK:-false}"
export PLANNING_TIMEOUT_SEC="${PLANNING_TIMEOUT_SEC:-120}"

if [ "$#" -eq 0 ]; then
  exec "$WS/start_llm_rekep_demo.sh" start
fi

exec "$WS/start_llm_rekep_demo.sh" "$@"
